---
language: node_js
node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - "npm install"

after_success:

script:
  - npm test

branches:
  only:
    - master

env:
  global:
    - DISABLE_SOURCE_MAPS=true
